In [157]:
import numpy as np
import pandas as pd
import os
import joblib

# Load each .npy file and convert the list of dictionaries to a DataFrame
dataframes = []
for file in os.listdir('dataset'):
    if file.endswith('.npy'):
        data = np.load('dataset/' + file, allow_pickle=True)
        dataframes.append(pd.DataFrame.from_records(data))

# Concatenate all DataFrames into a single DataFrame
merged_df = pd.concat(dataframes, ignore_index=True)
merged_df

Word  Frame      Px00      Py00      Pz00      Px09      Py09      Pz09  \
0      Boy      1  0.398471  0.235037 -0.283166  0.411580  0.261549 -0.261692   
1      Boy      2  0.386478  0.231599 -0.185648  0.403071  0.257796 -0.187297   
2      Boy      3  0.376553  0.231958 -0.165820  0.394055  0.258675 -0.171260   
3      Boy      4  0.376688  0.233247 -0.168176  0.392909  0.260331 -0.161914   
4      Boy      5  0.381708  0.233669 -0.091934  0.398634  0.261253 -0.104196   
...    ...    ...       ...       ...       ...       ...       ...       ...   
38874  You     16  0.542189  0.136061 -0.537967  0.554744  0.171417 -0.428920   
38875  You     17  0.555268  0.133114 -0.621718  0.565863  0.168493 -0.509749   
38876  You     18  0.558224  0.129539 -0.800129  0.569561  0.165968 -0.671478   
38877  You     19  0.558201  0.129194 -0.829248  0.570224  0.165823 -0.699506   
38878  You     20  0.563811  0.124503 -0.829559  0.576831  0.160924 -0.700145   

           Px10      Py10  ...      Rz13      Rx16      Ry16      Rz16  \
0      0.400813  0.262031  ...       NaN       NaN       NaN       NaN   
1      0.391257  0.259652  ...       NaN       NaN       NaN       NaN   
2      0.381407  0.262095  ...       NaN       NaN       NaN       NaN   
3      0.380841  0.265097  ...       NaN       NaN       NaN       NaN   
4      0.386369  0.262069  ...       NaN       NaN       NaN       NaN   
...         ...       ...  ...       ...       ...       ...       ...   
38874  0.519590  0.170560  ...  0.011044  0.738518  0.865947  0.006979   
38875  0.531135  0.168597  ...  0.009599  0.744591  0.860711  0.006831   
38876  0.533312  0.165906  ...  0.007862  0.747976  0.860318  0.004090   
38877  0.533202  0.165818  ...  0.006777  0.750997  0.861762  0.003672   
38878  0.537518  0.162081  ...  0.002093  0.750692  0.860353 -0.000819   

           Rx17      Ry17      Rz17      Rx20      Ry20      Rz20  
0           NaN       NaN       NaN       NaN       NaN       NaN  
1           NaN       NaN       NaN       NaN       NaN       NaN  
2           NaN       NaN       NaN       NaN       NaN       NaN  
3           NaN       NaN       NaN       NaN       NaN       NaN  
4           NaN       NaN       NaN       NaN       NaN       NaN  
...         ...       ...       ...       ...       ...       ...  
38874  0.767333  0.866118  0.017652  0.740954  0.865014  0.017385  
38875  0.772428  0.864244  0.014903  0.746699  0.861425  0.016022  
38876  0.776972  0.865593  0.013756  0.750843  0.860842  0.013237  
38877  0.778912  0.866651  0.012443  0.753333  0.862122  0.012391  
38878  0.781203  0.867767  0.007469  0.753249  0.861995  0.007263  

[38879 rows x 113 columns]

In [158]:
max_sequence_length = merged_df['Frame'].max()
max_sequence_length

20

In [159]:
merged_df = merged_df[merged_df['Frame'] != 20]
merged_df



Word  Frame      Px00      Py00      Pz00      Px09      Py09      Pz09  \
0      Boy      1  0.398471  0.235037 -0.283166  0.411580  0.261549 -0.261692   
1      Boy      2  0.386478  0.231599 -0.185648  0.403071  0.257796 -0.187297   
2      Boy      3  0.376553  0.231958 -0.165820  0.394055  0.258675 -0.171260   
3      Boy      4  0.376688  0.233247 -0.168176  0.392909  0.260331 -0.161914   
4      Boy      5  0.381708  0.233669 -0.091934  0.398634  0.261253 -0.104196   
...    ...    ...       ...       ...       ...       ...       ...       ...   
38873  You     15  0.538804  0.138693 -0.425125  0.551375  0.173030 -0.307523   
38874  You     16  0.542189  0.136061 -0.537967  0.554744  0.171417 -0.428920   
38875  You     17  0.555268  0.133114 -0.621718  0.565863  0.168493 -0.509749   
38876  You     18  0.558224  0.129539 -0.800129  0.569561  0.165968 -0.671478   
38877  You     19  0.558201  0.129194 -0.829248  0.570224  0.165823 -0.699506   

           Px10      Py10  ...      Rz13      Rx16      Ry16      Rz16  \
0      0.400813  0.262031  ...       NaN       NaN       NaN       NaN   
1      0.391257  0.259652  ...       NaN       NaN       NaN       NaN   
2      0.381407  0.262095  ...       NaN       NaN       NaN       NaN   
3      0.380841  0.265097  ...       NaN       NaN       NaN       NaN   
4      0.386369  0.262069  ...       NaN       NaN       NaN       NaN   
...         ...       ...  ...       ...       ...       ...       ...   
38873  0.516730  0.171964  ...  0.011003  0.732515  0.866298  0.007460   
38874  0.519590  0.170560  ...  0.011044  0.738518  0.865947  0.006979   
38875  0.531135  0.168597  ...  0.009599  0.744591  0.860711  0.006831   
38876  0.533312  0.165906  ...  0.007862  0.747976  0.860318  0.004090   
38877  0.533202  0.165818  ...  0.006777  0.750997  0.861762  0.003672   

           Rx17      Ry17      Rz17      Rx20      Ry20      Rz20  
0           NaN       NaN       NaN       NaN       NaN       NaN  
1           NaN       NaN       NaN       NaN       NaN       NaN  
2           NaN       NaN       NaN       NaN       NaN       NaN  
3           NaN       NaN       NaN       NaN       NaN       NaN  
4           NaN       NaN       NaN       NaN       NaN       NaN  
...         ...       ...       ...       ...       ...       ...  
38873  0.762894  0.866293  0.018535  0.735277  0.866190  0.018553  
38874  0.767333  0.866118  0.017652  0.740954  0.865014  0.017385  
38875  0.772428  0.864244  0.014903  0.746699  0.861425  0.016022  
38876  0.776972  0.865593  0.013756  0.750843  0.860842  0.013237  
38877  0.778912  0.866651  0.012443  0.753333  0.862122  0.012391  

[37696 rows x 113 columns]

In [160]:
padded_df = merged_df.reset_index(drop=True)
padded_df

Word  Frame      Px00      Py00      Pz00      Px09      Py09      Pz09  \
0      Boy      1  0.398471  0.235037 -0.283166  0.411580  0.261549 -0.261692   
1      Boy      2  0.386478  0.231599 -0.185648  0.403071  0.257796 -0.187297   
2      Boy      3  0.376553  0.231958 -0.165820  0.394055  0.258675 -0.171260   
3      Boy      4  0.376688  0.233247 -0.168176  0.392909  0.260331 -0.161914   
4      Boy      5  0.381708  0.233669 -0.091934  0.398634  0.261253 -0.104196   
...    ...    ...       ...       ...       ...       ...       ...       ...   
37691  You     15  0.538804  0.138693 -0.425125  0.551375  0.173030 -0.307523   
37692  You     16  0.542189  0.136061 -0.537967  0.554744  0.171417 -0.428920   
37693  You     17  0.555268  0.133114 -0.621718  0.565863  0.168493 -0.509749   
37694  You     18  0.558224  0.129539 -0.800129  0.569561  0.165968 -0.671478   
37695  You     19  0.558201  0.129194 -0.829248  0.570224  0.165823 -0.699506   

           Px10      Py10  ...      Rz13      Rx16      Ry16      Rz16  \
0      0.400813  0.262031  ...       NaN       NaN       NaN       NaN   
1      0.391257  0.259652  ...       NaN       NaN       NaN       NaN   
2      0.381407  0.262095  ...       NaN       NaN       NaN       NaN   
3      0.380841  0.265097  ...       NaN       NaN       NaN       NaN   
4      0.386369  0.262069  ...       NaN       NaN       NaN       NaN   
...         ...       ...  ...       ...       ...       ...       ...   
37691  0.516730  0.171964  ...  0.011003  0.732515  0.866298  0.007460   
37692  0.519590  0.170560  ...  0.011044  0.738518  0.865947  0.006979   
37693  0.531135  0.168597  ...  0.009599  0.744591  0.860711  0.006831   
37694  0.533312  0.165906  ...  0.007862  0.747976  0.860318  0.004090   
37695  0.533202  0.165818  ...  0.006777  0.750997  0.861762  0.003672   

           Rx17      Ry17      Rz17      Rx20      Ry20      Rz20  
0           NaN       NaN       NaN       NaN       NaN       NaN  
1           NaN       NaN       NaN       NaN       NaN       NaN  
2           NaN       NaN       NaN       NaN       NaN       NaN  
3           NaN       NaN       NaN       NaN       NaN       NaN  
4           NaN       NaN       NaN       NaN       NaN       NaN  
...         ...       ...       ...       ...       ...       ...  
37691  0.762894  0.866293  0.018535  0.735277  0.866190  0.018553  
37692  0.767333  0.866118  0.017652  0.740954  0.865014  0.017385  
37693  0.772428  0.864244  0.014903  0.746699  0.861425  0.016022  
37694  0.776972  0.865593  0.013756  0.750843  0.860842  0.013237  
37695  0.778912  0.866651  0.012443  0.753333  0.862122  0.012391  

[37696 rows x 113 columns]

In [161]:
# Define the columns to normalize
x_columns = ['Px00', 'Px09', 'Px10', 'Px11', 'Px12', 'Px13', 'Px14', 'Px15', 'Px16', 'Px17', 'Px18', 'Px19', 'Px20', 'Px21', 'Px22', 'Lx00', 'Lx01', 'Lx04', 'Lx05', 'Lx08', 'Lx09', 'Lx12', 'Lx13', 'Lx16', 'Lx17', 'Lx20', 'Rx00', 'Rx01', 'Rx04', 'Rx05', 'Rx08', 'Rx09', 'Rx12', 'Rx13', 'Rx16', 'Rx17', 'Rx20']
y_columns = ['Py00', 'Py09', 'Py10', 'Py11', 'Py12', 'Py13', 'Py14', 'Py15', 'Py16', 'Py17', 'Py18', 'Py19', 'Py20', 'Py21', 'Py22', 'Ly00', 'Ly01', 'Ly04', 'Ly05', 'Ly08', 'Ly09', 'Ly12', 'Ly13', 'Ly16', 'Ly17', 'Ly20', 'Ry00', 'Ry01', 'Ry04', 'Ry05', 'Ry08', 'Ry09', 'Ry12', 'Ry13', 'Ry16', 'Ry17', 'Ry20']
z_columns = ['Pz00', 'Pz09', 'Pz10', 'Pz11', 'Pz12', 'Pz13', 'Pz14', 'Pz15', 'Pz16', 'Pz17', 'Pz18', 'Pz19', 'Pz20', 'Pz21', 'Pz22', 'Lz00', 'Lz01', 'Lz04', 'Lz05', 'Lz08', 'Lz09', 'Lz12', 'Lz13', 'Lz16', 'Lz17', 'Lz20', 'Rz00', 'Rz01', 'Rz04', 'Rz05', 'Rz08', 'Rz09', 'Rz12', 'Rz13', 'Rz16', 'Rz17', 'Rz20']

padded_df[x_columns] = padded_df[x_columns].fillna(padded_df[x_columns].mean())
padded_df[y_columns] = padded_df[y_columns].fillna(1.2)
padded_df[z_columns] = padded_df[z_columns].fillna(padded_df[z_columns].mean())
padded_df


Word  Frame      Px00      Py00      Pz00      Px09      Py09      Pz09  \
0      Boy      1  0.398471  0.235037 -0.283166  0.411580  0.261549 -0.261692   
1      Boy      2  0.386478  0.231599 -0.185648  0.403071  0.257796 -0.187297   
2      Boy      3  0.376553  0.231958 -0.165820  0.394055  0.258675 -0.171260   
3      Boy      4  0.376688  0.233247 -0.168176  0.392909  0.260331 -0.161914   
4      Boy      5  0.381708  0.233669 -0.091934  0.398634  0.261253 -0.104196   
...    ...    ...       ...       ...       ...       ...       ...       ...   
37691  You     15  0.538804  0.138693 -0.425125  0.551375  0.173030 -0.307523   
37692  You     16  0.542189  0.136061 -0.537967  0.554744  0.171417 -0.428920   
37693  You     17  0.555268  0.133114 -0.621718  0.565863  0.168493 -0.509749   
37694  You     18  0.558224  0.129539 -0.800129  0.569561  0.165968 -0.671478   
37695  You     19  0.558201  0.129194 -0.829248  0.570224  0.165823 -0.699506   

           Px10      Py10  ...      Rz13      Rx16      Ry16      Rz16  \
0      0.400813  0.262031  ... -0.008956  0.567531  1.200000 -0.012851   
1      0.391257  0.259652  ... -0.008956  0.567531  1.200000 -0.012851   
2      0.381407  0.262095  ... -0.008956  0.567531  1.200000 -0.012851   
3      0.380841  0.265097  ... -0.008956  0.567531  1.200000 -0.012851   
4      0.386369  0.262069  ... -0.008956  0.567531  1.200000 -0.012851   
...         ...       ...  ...       ...       ...       ...       ...   
37691  0.516730  0.171964  ...  0.011003  0.732515  0.866298  0.007460   
37692  0.519590  0.170560  ...  0.011044  0.738518  0.865947  0.006979   
37693  0.531135  0.168597  ...  0.009599  0.744591  0.860711  0.006831   
37694  0.533312  0.165906  ...  0.007862  0.747976  0.860318  0.004090   
37695  0.533202  0.165818  ...  0.006777  0.750997  0.861762  0.003672   

           Rx17      Ry17      Rz17      Rx20      Ry20      Rz20  
0      0.589461  1.200000 -0.008864  0.572594  1.200000 -0.010037  
1      0.589461  1.200000 -0.008864  0.572594  1.200000 -0.010037  
2      0.589461  1.200000 -0.008864  0.572594  1.200000 -0.010037  
3      0.589461  1.200000 -0.008864  0.572594  1.200000 -0.010037  
4      0.589461  1.200000 -0.008864  0.572594  1.200000 -0.010037  
...         ...       ...       ...       ...       ...       ...  
37691  0.762894  0.866293  0.018535  0.735277  0.866190  0.018553  
37692  0.767333  0.866118  0.017652  0.740954  0.865014  0.017385  
37693  0.772428  0.864244  0.014903  0.746699  0.861425  0.016022  
37694  0.776972  0.865593  0.013756  0.750843  0.860842  0.013237  
37695  0.778912  0.866651  0.012443  0.753333  0.862122  0.012391  

[37696 rows x 113 columns]

In [162]:
# Normalize the x columns
padded_df[x_columns] = padded_df[x_columns].div(padded_df['Px12'], axis=0)

# Normalize the y columns
padded_df[y_columns] = padded_df[y_columns].div(padded_df['Py12'], axis=0)

# Normalize the z columns
padded_df[z_columns] = padded_df[z_columns].div(padded_df['Pz12'], axis=0)

padded_df

Word  Frame      Px00      Py00      Pz00      Px09      Py09      Pz09  \
0      Boy      1  1.014135  0.598821 -3.607023  1.047498  0.666369 -3.333487   
1      Boy      2  0.970518  0.576860 -1.207271  1.012186  0.642110 -1.217989   
2      Boy      3  0.946956  0.557164 -0.933967  0.990968  0.621340 -0.964605   
3      Boy      4  0.972168  0.571683 -0.983888  1.014031  0.638066 -0.947253   
4      Boy      5  0.960911  0.606929 -0.557010  1.003521  0.678574 -0.631297   
...    ...    ...       ...       ...       ...       ...       ...       ...   
37691  You     15  1.373249  0.490870  2.052701  1.405290  0.612394  1.484865   
37692  You     16  1.378725  0.482035  2.126669  1.410651  0.607296  1.695591   
37693  You     17  1.426016  0.453331  2.037752  1.453225  0.573818  1.670760   
37694  You     18  1.448891  0.424667  1.985702  1.478318  0.544091  1.666425   
37695  You     19  1.448603  0.424739  2.020705  1.479805  0.545159  1.704551   

           Px10      Py10  ...      Rz13      Rx16      Ry16      Rz16  \
0      1.020096  0.667596  ... -0.114083  1.444402  3.057331 -0.163699   
1      0.982519  0.646734  ... -0.058241  1.425176  2.988923 -0.083570   
2      0.959161  0.629554  ... -0.050444  1.427226  2.882408 -0.072382   
3      0.982887  0.649749  ... -0.052396  1.464700  2.941177 -0.075183   
4      0.972645  0.680695  ... -0.054262  1.428700  3.116863 -0.077861   
...         ...       ...  ...       ...       ...       ...       ...   
37691  1.316990  0.608623  ... -0.053127  1.866960  3.066039 -0.036021   
37692  1.321258  0.604260  ... -0.043657  1.877968  3.067873 -0.027589   
37693  1.364038  0.574170  ... -0.031463  1.912227  2.931226 -0.022390   
37694  1.384233  0.543890  ... -0.019513  1.941402  2.820380 -0.010149   
37695  1.383729  0.545142  ... -0.016513  1.948936  2.833132 -0.008947   

           Rx17      Ry17      Rz17      Rx20      Ry20      Rz20  
0      1.500217  3.057331 -0.112917  1.457288  3.057331 -0.127850  
1      1.480248  2.988923 -0.057646  1.437891  2.988923 -0.065269  
2      1.482376  2.882408 -0.049928  1.439959  2.882408 -0.056531  
3      1.521299  2.941177 -0.051860  1.477767  2.941177 -0.058718  
4      1.483907  3.116863 -0.053708  1.441446  3.116863 -0.060810  
...         ...       ...       ...       ...       ...       ...  
37691  1.944387  3.066023 -0.089494  1.874000  3.065660 -0.089585  
37692  1.951240  3.068479 -0.069780  1.884162  3.064565 -0.068725  
37693  1.983716  2.943256 -0.048845  1.917640  2.933655 -0.052514  
37694  2.016661  2.837672 -0.034138  1.948843  2.822096 -0.032850  
37695  2.021378  2.849203 -0.030320  1.954997  2.834313 -0.030194  

[37696 rows x 113 columns]

In [163]:
# Normalize the x columns
padded_df[x_columns] = padded_df[x_columns].sub(padded_df['Px11'], axis=0)

# Normalize the y columns
padded_df[y_columns] = padded_df[y_columns].sub(padded_df['Py11'], axis=0)

# Normalize the z columns
padded_df[z_columns] = padded_df[z_columns].sub(padded_df['Pz11'], axis=0)

padded_df

Word  Frame      Px00      Py00      Pz00      Px09      Py09      Pz09  \
0      Boy      1 -0.287046 -0.322529 -0.134225 -0.253682 -0.254981  0.139311   
1      Boy      2 -0.308797 -0.315106  0.643916 -0.267129 -0.249856  0.633198   
2      Boy      3 -0.298802 -0.299563  0.759762 -0.254790 -0.235387  0.729123   
3      Boy      4 -0.301871 -0.296082  0.424481 -0.260009 -0.229699  0.461115   
4      Boy      5 -0.264300 -0.277385  0.947159 -0.221690 -0.205741  0.872872   
...    ...    ...       ...       ...       ...       ...       ...       ...   
37691  You     15 -0.293952 -0.606560  2.478790 -0.261911 -0.485036  1.910954   
37692  You     16 -0.300683 -0.650089  2.085527 -0.268757 -0.524828  1.654449   
37693  You     17 -0.289572 -0.635016  1.741572 -0.262363 -0.514529  1.374580   
37694  You     18 -0.308322 -0.622111  1.547822 -0.278895 -0.502687  1.228545   
37695  You     19 -0.312742 -0.623408  1.538963 -0.281539 -0.502988  1.222809   

           Px10      Py10  ...      Rz13      Rx16      Ry16      Rz16  \
0     -0.281085 -0.253754  ...  3.358715  0.143222  2.135981  3.309099   
1     -0.296797 -0.245231  ...  1.792946  0.145861  2.096957  1.767617   
2     -0.286598 -0.227173  ...  1.643285  0.181467  2.025681  1.621346   
3     -0.291153 -0.218017  ...  1.355973  0.190661  2.073412  1.333185   
4     -0.252567 -0.203619  ...  1.449907  0.203489  2.232548  1.426308   
...         ...       ...  ...       ...       ...       ...       ...   
37691 -0.350211 -0.488807  ...  0.372961  0.199759  1.968610  0.390068   
37692 -0.358150 -0.527864  ... -0.084799  0.198560  1.935749 -0.068730   
37693 -0.351551 -0.514177  ... -0.327642  0.196639  1.842879 -0.318570   
37694 -0.372981 -0.502888  ... -0.457392  0.184189  1.773602 -0.448028   
37695 -0.377616 -0.503004  ... -0.498255  0.187591  1.784985 -0.490689   

           Rx17      Ry17      Rz17      Rx20      Ry20      Rz20  
0      0.199036  2.135981  3.359880  0.156108  2.135981  3.344948  
1      0.200932  2.096957  1.793541  0.158576  2.096957  1.785918  
2      0.236618  2.025681  1.643800  0.194200  2.025681  1.637198  
3      0.247260  2.073412  1.356508  0.203728  2.073412  1.349650  
4      0.258696  2.232548  1.450461  0.216235  2.232548  1.443359  
...         ...       ...       ...       ...       ...       ...  
37691  0.277186  1.968593  0.336595  0.206799  1.968230  0.336504  
37692  0.271832  1.936355 -0.110922  0.204755  1.932441 -0.109867  
37693  0.268128  1.854909 -0.345025  0.202051  1.845308 -0.348693  
37694  0.259447  1.790894 -0.472018  0.191630  1.775318 -0.470729  
37695  0.260034  1.801056 -0.512062  0.193652  1.786166 -0.511936  

[37696 rows x 113 columns]

In [164]:
padded_df

Word  Frame      Px00      Py00      Pz00      Px09      Py09      Pz09  \
0      Boy      1 -0.287046 -0.322529 -0.134225 -0.253682 -0.254981  0.139311   
1      Boy      2 -0.308797 -0.315106  0.643916 -0.267129 -0.249856  0.633198   
2      Boy      3 -0.298802 -0.299563  0.759762 -0.254790 -0.235387  0.729123   
3      Boy      4 -0.301871 -0.296082  0.424481 -0.260009 -0.229699  0.461115   
4      Boy      5 -0.264300 -0.277385  0.947159 -0.221690 -0.205741  0.872872   
...    ...    ...       ...       ...       ...       ...       ...       ...   
37691  You     15 -0.293952 -0.606560  2.478790 -0.261911 -0.485036  1.910954   
37692  You     16 -0.300683 -0.650089  2.085527 -0.268757 -0.524828  1.654449   
37693  You     17 -0.289572 -0.635016  1.741572 -0.262363 -0.514529  1.374580   
37694  You     18 -0.308322 -0.622111  1.547822 -0.278895 -0.502687  1.228545   
37695  You     19 -0.312742 -0.623408  1.538963 -0.281539 -0.502988  1.222809   

           Px10      Py10  ...      Rz13      Rx16      Ry16      Rz16  \
0     -0.281085 -0.253754  ...  3.358715  0.143222  2.135981  3.309099   
1     -0.296797 -0.245231  ...  1.792946  0.145861  2.096957  1.767617   
2     -0.286598 -0.227173  ...  1.643285  0.181467  2.025681  1.621346   
3     -0.291153 -0.218017  ...  1.355973  0.190661  2.073412  1.333185   
4     -0.252567 -0.203619  ...  1.449907  0.203489  2.232548  1.426308   
...         ...       ...  ...       ...       ...       ...       ...   
37691 -0.350211 -0.488807  ...  0.372961  0.199759  1.968610  0.390068   
37692 -0.358150 -0.527864  ... -0.084799  0.198560  1.935749 -0.068730   
37693 -0.351551 -0.514177  ... -0.327642  0.196639  1.842879 -0.318570   
37694 -0.372981 -0.502888  ... -0.457392  0.184189  1.773602 -0.448028   
37695 -0.377616 -0.503004  ... -0.498255  0.187591  1.784985 -0.490689   

           Rx17      Ry17      Rz17      Rx20      Ry20      Rz20  
0      0.199036  2.135981  3.359880  0.156108  2.135981  3.344948  
1      0.200932  2.096957  1.793541  0.158576  2.096957  1.785918  
2      0.236618  2.025681  1.643800  0.194200  2.025681  1.637198  
3      0.247260  2.073412  1.356508  0.203728  2.073412  1.349650  
4      0.258696  2.232548  1.450461  0.216235  2.232548  1.443359  
...         ...       ...       ...       ...       ...       ...  
37691  0.277186  1.968593  0.336595  0.206799  1.968230  0.336504  
37692  0.271832  1.936355 -0.110922  0.204755  1.932441 -0.109867  
37693  0.268128  1.854909 -0.345025  0.202051  1.845308 -0.348693  
37694  0.259447  1.790894 -0.472018  0.191630  1.775318 -0.470729  
37695  0.260034  1.801056 -0.512062  0.193652  1.786166 -0.511936  

[37696 rows x 113 columns]

In [165]:
padded_df = padded_df[['Word', 'Frame'] + x_columns + y_columns + z_columns]
padded_df

Word  Frame      Px00      Px09      Px10  Px11      Px12      Px13  \
0      Boy      1 -0.287046 -0.253682 -0.281085   0.0 -0.301181  0.048500   
1      Boy      2 -0.308797 -0.267129 -0.296797   0.0 -0.279315  0.056343   
2      Boy      3 -0.298802 -0.254790 -0.286598   0.0 -0.245758  0.098630   
3      Boy      4 -0.301871 -0.260009 -0.291153   0.0 -0.274039 -0.023749   
4      Boy      5 -0.264300 -0.221690 -0.252567   0.0 -0.225211 -0.030780   
...    ...    ...       ...       ...       ...   ...       ...       ...   
37691  You     15 -0.293952 -0.261911 -0.350211   0.0 -0.667201  0.114403   
37692  You     16 -0.300683 -0.268757 -0.358150   0.0 -0.679408  0.123895   
37693  You     17 -0.289572 -0.262363 -0.351551   0.0 -0.715589  0.113324   
37694  You     18 -0.308322 -0.278895 -0.372981   0.0 -0.757214  0.105447   
37695  You     19 -0.312742 -0.281539 -0.377616   0.0 -0.761345  0.104186   

           Px14      Px15  ...      Rz01      Rz04      Rz05      Rz08  \
0     -0.300209 -0.179907  ...  3.380520  3.261819  3.336378  3.172682   
1     -0.310748 -0.225717  ...  1.804078  1.743480  1.781543  1.697975   
2     -0.299167 -0.222121  ...  1.652927  1.600441  1.633409  1.561028   
3     -0.331679 -0.319043  ...  1.365988  1.311471  1.345714  1.270532   
4     -0.256949 -0.240926  ...  1.460279  1.403820  1.439283  1.361423   
...         ...       ...  ...       ...       ...       ...       ...   
37691 -0.629807  0.234629  ...  0.521291  0.523243  0.468206  0.504961   
37692 -0.679303  0.239605  ...  0.031048  0.030581 -0.014721  0.022081   
37693 -0.702071  0.231244  ... -0.239839 -0.246303 -0.277751 -0.246184   
37694 -0.740219  0.222452  ... -0.391038 -0.388777 -0.416360 -0.386544   
37695 -0.745278  0.223094  ... -0.439118 -0.439097 -0.460229 -0.433058   

           Rz09      Rz12      Rz13      Rz16      Rz17      Rz20  
0      3.350309  3.238965  3.358715  3.309099  3.359880  3.344948  
1      1.788655  1.731813  1.792946  1.767617  1.793541  1.785918  
2      1.639568  1.590336  1.643285  1.621346  1.643800  1.637198  
3      1.352112  1.300975  1.355973  1.333185  1.356508  1.349650  
4      1.445909  1.392950  1.449907  1.426308  1.450461  1.443359  
...         ...       ...       ...       ...       ...       ...  
37691  0.416095  0.440633  0.372961  0.390068  0.336595  0.336504  
37692 -0.053366 -0.026675 -0.084799 -0.068730 -0.110922 -0.109867  
37693 -0.305870 -0.286396 -0.327642 -0.318570 -0.345025 -0.348693  
37694 -0.439324 -0.421452 -0.457392 -0.448028 -0.472018 -0.470729  
37695 -0.481308 -0.465112 -0.498255 -0.490689 -0.512062 -0.511936  

[37696 rows x 113 columns]

In [166]:
from sklearn.preprocessing import MinMaxScaler

data = padded_df.drop('Word', axis=1)
target = padded_df['Word']

# Normalize data
scaler = MinMaxScaler(feature_range=(0, 1))

features_scaled = scaler.fit_transform(data)
joblib.dump(scaler, 'scaler.gz')

features_scaled

array([[0.        , 0.89107013, 0.88413694, ..., 0.69070272, 0.67035741,
        0.68819825],
       [0.05555556, 0.88651698, 0.8806922 , ..., 0.69066593, 0.67032206,
        0.68816272],
       [0.11111111, 0.88860914, 0.88385313, ..., 0.69066244, 0.67031868,
        0.68815933],
       ...,
       [0.88888889, 0.89054121, 0.88191302, ..., 0.69061613, 0.6702738 ,
        0.68811408],
       [0.94444444, 0.88661642, 0.87767794, ..., 0.69061304, 0.67027093,
        0.6881113 ],
       [1.        , 0.88569129, 0.87700069, ..., 0.69061203, 0.67027003,
        0.68811036]])

In [167]:
# Define the number of time steps
time_steps = 19

# Prepare the data
X = []
y = []

for i in range(0, len(features_scaled) - time_steps + 1, time_steps):
    X.append(features_scaled[i:i + time_steps])
    y.append(target[i])

# Convert to NumPy arrays
X = np.array(X)
y = np.array(y)

# Reshape X to fit the LSTM input shape: [samples, time steps, features]
X = X.reshape((1984, time_steps, 112))
print(X)

[[[0.         0.89107013 0.88413694 ... 0.69070272 0.67035741 0.68819825]
  [0.05555556 0.88651698 0.8806922  ... 0.69066593 0.67032206 0.68816272]
  [0.11111111 0.88860914 0.88385313 ... 0.69066244 0.67031868 0.68815933]
  ...
  [0.88888889 0.89298748 0.88695976 ... 0.69066695 0.67032307 0.68816308]
  [0.94444444 0.89360239 0.88775107 ... 0.69066626 0.67032247 0.68816236]
  [1.         0.89402216 0.8882611  ... 0.69065949 0.67031598 0.68815599]]

 [[0.         0.82462626 0.81751335 ... 0.69066212 0.6703182  0.6881589 ]
  [0.05555556 0.82149588 0.81527204 ... 0.69066722 0.67032304 0.68816378]
  [0.11111111 0.82100144 0.81792327 ... 0.69065646 0.67031283 0.68815349]
  ...
  [0.88888889 0.82039277 0.81072831 ... 0.69066487 0.67032111 0.68816111]
  [0.94444444 0.82116725 0.81195805 ... 0.69065941 0.67031625 0.68815581]
  [1.         0.82070906 0.81136739 ... 0.69066184 0.67031859 0.6881583 ]]

 [[0.         0.92711355 0.92450364 ... 0.69060797 0.67026699 0.6881072 ]
  [0.05555556 0.947227

In [168]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [169]:
from sklearn.preprocessing import LabelEncoder

# Assuming 'y_train' is your target variable with categorical values
encoder = LabelEncoder()
y_train_encoded = encoder.fit_transform(y_train)
y_test_encoded = encoder.transform(y_test)

LSTM

In [170]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras import backend as K
import tensorflow as tf
from keras.optimizers import Adam


# Assuming X_train has shape (num_samples, timesteps, features)
timesteps = X_train.shape[1]
features = X_train.shape[2]
num_classes = len(encoder.classes_)

model = Sequential()
model.add(LSTM(64, return_sequences=True, input_shape=(timesteps, features)))
model.add(Dropout(0.2))
model.add(LSTM(32, return_sequences=False))
model.add(Dropout(0.2))
model.add(Dense(num_classes, activation='softmax'))

optimizer = Adam(clipvalue=1.0) 
model.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy', metrics=['accuracy'])

print(model.summary())

c:\Users\Mello\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\rnn\rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_18"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_36 (LSTM)                  │ (None, 19, 64)         │        45,312 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_34 (Dropout)            │ (None, 19, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_37 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_35 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_18 (Dense)                │ (None, 13)             │           429 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 58,157 (227.18 KB)

 Trainable params: 58,157 (227.18 KB)

 Non-trainable params: 0 (0.00 B)

None


In [171]:

history = model.fit(X_train, y_train_encoded, epochs=70, batch_size=32, validation_split=0.2)

Epoch 1/70
40/40 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - accuracy: 0.0788 - loss: 2.5804 - val_accuracy: 0.1509 - val_loss: 2.4648
Epoch 2/70
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.1866 - loss: 2.4074 - val_accuracy: 0.1824 - val_loss: 2.2545
Epoch 3/70
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.2160 - loss: 2.2403 - val_accuracy: 0.1258 - val_loss: 2.4151
Epoch 4/70
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.2463 - loss: 2.1218 - val_accuracy: 0.3333 - val_loss: 1.8085
Epoch 5/70
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.3355 - loss: 1.7839 - val_accuracy: 0.3491 - val_loss: 1.7006
Epoch 6/70
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.3569 - loss: 1.7489 - val_accuracy: 0.4025 - val_loss: 1.7240
Epoch 7/70
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4101 - loss: 1.6120 - val_accuracy: 0.3962 - val_loss: 1.6049
Epoch 8/70
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.4253 - loss: 1.5203 - val_accuracy: 0.3491 - val_lo

In [172]:
test_loss, test_accuracy = model.evaluate(X_test, y_test_encoded)
print(f"Test Loss: {test_loss}, Test Accuracy: {test_accuracy}")

13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8551 - loss: 0.4416  
Test Loss: 0.4613499045372009, Test Accuracy: 0.8488665223121643


In [173]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test) # Replace `model` with your trained LSTM model and `X_test` with your test dataset
y_pred_labels = np.argmax(y_pred, axis=1)
# Print the classification report
print(classification_report(y_test_encoded, y_pred_labels))

13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
              precision    recall  f1-score   support

           0       0.79      0.85      0.82        40
           1       0.94      0.94      0.94        34
           2       0.74      0.57      0.64        30
           3       0.97      0.97      0.97        35
           4       0.73      0.63      0.68        30
           5       0.97      0.97      0.97        33
           6       0.77      0.94      0.85        18
           7       0.79      1.00      0.88        26
           8       0.80      0.48      0.60        25
           9       0.95      0.91      0.93        22
          10       0.86      1.00      0.93        32
          11       0.91      0.83      0.87        35
          12       0.77      0.89      0.82        37

    accuracy                           0.85       397
   macro avg       0.85      0.85      0.84       397
weighted avg       0.85      0.85      0.84       397



In [174]:
model.feature_names = padded_df.iloc[:, 1:].columns
model.feature_names


Index(['Frame', 'Px00', 'Px09', 'Px10', 'Px11', 'Px12', 'Px13', 'Px14', 'Px15',
       'Px16',
       ...
       'Rz01', 'Rz04', 'Rz05', 'Rz08', 'Rz09', 'Rz12', 'Rz13', 'Rz16', 'Rz17',
       'Rz20'],
      dtype='object', length=112)

In [175]:
import tensorflow as tf

model.save('lstmmodel.keras')
tf.saved_model.save(model, 'saved_model')

INFO:tensorflow:Assets written to: saved_model\assets


INFO:tensorflow:Assets written to: saved_model\assets


In [176]:
import numpy as np

# Ensure model weights are properly initialized
for layer in model.layers:
    weights = layer.get_weights()
    for weight in weights:
        if np.isnan(weight).any():
            raise ValueError(f"Weights in layer {layer.name} contain NaNs")